-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT into profile_roles (value, description) VALUES
-- ('MemberWhoCanList', 'Members who can list profiles');
