-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "user" (id, first_name, last_name, email, "type") VALUES
-- ('bot-BAZe9r-canopybot', 'Canopy', 'Bot', 'team+canopybot@joincanopy.org', 'Bot');
