-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO profile_types (value, description) VALUES
--   ('Banned', 'Profile is banned from space'),
--   ('Member', 'Normal members'),
--   ('Admin', 'Admins'),
--   ('SuperAdmin', 'Admins that can manage other admins');
