-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO "public"."space_attribute_type" (value, description) VALUES
-- ('ListingQuestionsOrder', 'Order of questions in space listings');
