table:
  name: chat_message
  schema: public
object_relationships:
  - name: chat_room
    using:
      foreign_key_constraint_on: chat_room_id
  - name: reply_to_message
    using:
      foreign_key_constraint_on: reply_to_message_id
  - name: sender_profile
    using:
      foreign_key_constraint_on: sender_profile_id
array_relationships:
  - name: message_replies
    using:
      foreign_key_constraint_on:
        column: reply_to_message_id
        table:
          name: chat_message
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - _and:
              - chat_room:
                  profile_to_chat_rooms:
                    profile:
                      user_id:
                        _eq: X-Hasura-User-Id
              - sender_profile:
                  user_id:
                    _eq: X-Hasura-User-Id
      columns:
        - chat_room_id
        - deleted
        - id
        - reply_to_message_id
        - sender_profile_id
        - text
select_permissions:
  - role: user
    permission:
      columns:
        - chat_room_id
        - created_at
        - deleted
        - id
        - is_system_message
        - metadata
        - reply_to_message_id
        - sender_profile_id
        - text
      filter:
        _or:
          - chat_room:
              profile_to_chat_rooms:
                profile:
                  user_id:
                    _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - deleted
      filter:
        sender_profile:
          user_id:
            _eq: X-Hasura-User-Id
      check: null
event_triggers:
  - name: on_chat_message_insert
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: CANOPY_EVENT_WEBHOOK_URL
    headers:
      - name: x-canopy-event-client-key
        value_from_env: CANOPY_EVENT_CLIENT_KEY
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
