table:
  name: profile_to_chat_room
  schema: public
object_relationships:
  - name: chat_room
    using:
      foreign_key_constraint_on: chat_room_id
  - name: profile
    using:
      foreign_key_constraint_on: profile_id
select_permissions:
  - role: user
    permission:
      columns:
        - chat_room_id
        - created_at
        - id
        - latest_read_chat_message_id
        - profile_id
      filter:
        _or:
          - chat_room:
              profile_to_chat_rooms:
                profile:
                  user_id:
                    _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - latest_read_chat_message_id
      filter:
        _or:
          - profile:
              user_id:
                _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - _and:
              - profile:
                  user_id:
                    _eq: X-Hasura-User-Id
event_triggers:
  - name: on_ptcr_update
    definition:
      enable_manual: false
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: CANOPY_EVENT_WEBHOOK_URL
    headers:
      - name: x-canopy-event-client-key
        value_from_env: CANOPY_EVENT_CLIENT_KEY
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
