-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."space_tag_category" add column "rigid_select" boolean
--  not null default 'true';
