-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO profile_listing_social_type (value, description) VALUES
-- ('LinkedIn', 'linkedin.com');
