-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."profiles" add column "listing_enabled" boolean
--  not null default 'false';
