-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."chat_room" add column "attributes" jsonb
--  not null default jsonb_build_object();
