-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."connection_request" add column "status" text
--  null default 'ConnectionRequestSent';
