version: "3.6"
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - canopy_prod_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
  graphql-engine:
    image: hasura/graphql-engine:v2.16.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - .env.prod

volumes:
  canopy_prod_db:
