-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."profile_to_chat_room" add column "latest_read_chat_message_id" bigint
--  null;
