-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."space_tag" add column "status" text
--  not null default 'Accepted';
