-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT into space_tag_status (value, description) VALUES
-- ('Pending', 'Pending Admin review.'),
-- ('Accepted', 'Shows in filter dropdown on home page'),
-- ('Rejected', 'Does not show in filter dropdown on home page');
