name: Hasura migrations (PROD)
on:
  push:
    branches:
      - main
    paths:
      - "hasura/**"

concurrency: prod_environment

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install Hasura CLI
        run: npm install --global hasura-cli@2.36.1

      - name: Apply Metadata
        working-directory: ./hasura
        run: hasura metadata apply --endpoint ${{ secrets.PROD_HASURA_ENDPOINT }} --admin-secret ${{ secrets.PROD_HASURA_ADMIN_SECRET }}

      - name: Print Migration Status
        working-directory: ./hasura
        run: hasura migrate status --database-name mentorcenter --endpoint ${{ secrets.PROD_HASURA_ENDPOINT }} --admin-secret ${{ secrets.PROD_HASURA_ADMIN_SECRET }}

      - name: Apply Migrations
        working-directory: ./hasura
        run: hasura migrate apply --all-databases --endpoint ${{ secrets.PROD_HASURA_ENDPOINT }} --admin-secret ${{ secrets.PROD_HASURA_ADMIN_SECRET }}

      - name: hasura metadata reload
        working-directory: ./hasura
        run: hasura metadata reload --endpoint ${{ secrets.PROD_HASURA_ENDPOINT }} --admin-secret ${{ secrets.PROD_HASURA_ADMIN_SECRET }}
